# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'
#
# specifying the language version tries to solve a bug in conda:
# https://stackoverflow.com/questions/72177222/runtimeerror-failed-to-find-interpreter-for-builtin-discover-of-python-spec-py
default_language_version:
    python: python3.10  # or python3

repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
       - id: isort
         args: ["--profile", "black"]
